export const surpriseMePrompts = [
  "A serene sunset over a futuristic cityscape with flying cars",
  "A whimsical garden with colorful talking animals",
  "A majestic dragon soaring through the clouds",
  "A group of friends enjoying a picnic under cherry blossom trees",
  "A mystical forest with glowing mushrooms and fairies",
  "A steampunk-inspired metropolis with clockwork machinery",
  "A peaceful seaside village with charming traditional houses",
  "A futuristic cyborg samurai wielding a glowing energy sword",
  "A young sorceress casting powerful spells in a magical library",
  "A breathtaking waterfall cascading into a hidden paradise",
  "A vibrant marketplace filled with exotic fruits and spices",
  "A haunted mansion with eerie ghosts and secret passageways",
  "A dazzling fireworks display illuminating the night sky",
  "A group of adventurers embarking on a perilous quest",
  "A whimsical carousel with intricately designed animals",
  "A majestic phoenix rising from the ashes",
  "A serene temple hidden in the mountains",
  "A playful cat with shimmering rainbow fur",
  "A futuristic cityscape with floating islands and airships",
  "A mesmerizing ballet performance in a grand theater",
  "A magical school for gifted witches and wizards",
  "A tranquil lake surrounded by colorful blooming flowers",
  "A brave warrior wielding a legendary enchanted sword",
  "A futuristic cyberpunk street with neon lights and holograms",
  "A mischievous fox spirit playing tricks on unsuspecting travelers",
  "A celestial kingdom in the clouds with floating castles",
  "A vibrant underwater world with coral reefs and exotic sea creatures",
  "A peaceful countryside with rolling hills and farm animals",
  "A group of heroes defending a city from a colossal monster",
  "A mystical floating island with waterfalls and floating gardens",
  "A whimsical tea party with talking animals and enchanted treats",
  "A futuristic mecha pilot in a high-tech cockpit",
  "A secret magical library filled with ancient books and artifacts",
  "A breathtaking starry sky with constellations and shooting stars",
  "A traditional Japanese onsen with hot springs and bamboo forests",
  "A magical forest inhabited by friendly forest spirits",
  "A grand castle perched on a mountaintop",
  "A lively street festival with vibrant decorations and music",
  "A serene bamboo forest with sunlight filtering through the trees",
  "A brave samurai battling a fearsome mythical creature",
  "A futuristic racing track with hovering vehicles",
  "A mysterious masked ball with elaborate costumes",
  "A peaceful zen garden with raked sand and bonsai trees",
  "A whimsical underwater city with mermaids and seahorse carriages",
  "A daring space explorer discovering alien landscapes",
  "A magical carnival with enchanting rides and attractions",
  "A tranquil meditation retreat in the mountains",
  "A mystical portal leading to another dimension",
  "A group of friends stargazing on a moonlit night",
  "A futuristic battle arena with advanced combat robots",
  "An armchair in the shape of an avocado",
  "A surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "Teddy bears shopping for groceries in Japan, ukiyo-e",
  "An oil painting by Matisse of a humanoid robot playing chess",
  "Panda mad scientist mixing sparkling chemicals, digital art",
  "A macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "An astronaut lounging in a tropical resort in space, vaporwave",
  "An oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "A stained glass window depicting a hamburger and french fries",
  "A pencil and watercolor drawing of a bright city in the future with flying cars",
  "A sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "A fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  "A sea otter with a pearl earring by Johannes Vermeer",
  "An oil pastel drawing of an annoyed cat in a spaceship",
  "A painting of a fox in the style of Starry Night",
  "A bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubiks cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave Aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "Design a piece of digital artwork showing an imagined colony on Mars",
  "Compose a collage of portraits of the Indian Prime Ministers",
  "Create an abstract painting inspired by the rush hour traffic in New York City",
];